CREATE TABLE Person(
	person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	name VARCHAR(100) NOT NULL,
	role VARCHAR(100) NOT NULL
);

CREATE TABLE Post(
	post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	created_at TIMESTAMP,
	person_id INT REFERENCES Person(person_id)
);

CREATE TABLE Friendship(
	friendship_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	receiver_id INT NOT NULL REFERENCES Person(person_id),
	subscriber_id INT NOT NULL REFERENCES Person(person_id),
	friendship_status VARCHAR NOT NULL,
	friendship_date TIMESTAMP
);

CREATE TABLE Message(
    message_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id INT NOT NULL REFERENCES Person(person_id),
    sender_id INT NOT NULL REFERENCES Person(person_id),
    content VARCHAR NOT NULL,
    sent_at TIMESTAMP
);